### ISSUE TITLE
Add tag when pushing to main

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/govpp#18]
### Description
Currently, we only tag images:
_ghcr.io/networkservicemesh/govpp/vpp:**v23.10-rc0-166-g4a6d39d90**_

It is also necessary to tag the commit from which this image was built.

**Comment by VitalyGushin** [comment]
Action plan for **including govpp into the NSM release**:

1. Add vpp version tagging for commit on every push into main branch
2. Add release workflow (support usual tagging with NSM release version)
3. Don’t exclude **/govpp** package from go.mod dependencies (check-gomod-deps.yaml)

**Example**:
1. Any push into main:
   a. Tag the last commit with the last vpp version like **v23.10-rc0-169-g7e1c880d6**
   b. Build the **govpp/vpp** image and tag it with the last vpp version like **v23.10-rc0-169-g7e1c880d6**
2. Release:
   a. Create a release branch like **release/v1.12.0**
   b. Tag the last commit with a release version like **v1.12.0**
   c. Build the **govpp/vpp** image and tag it with a release version like **v1.12.0**

cc @edwarnicke @denis-tingaikin @glazychev-art

**Comment by denis-tingaikin** [comment]
Seems like the scope is done.

Can be improved in the future https://github.com/networkservicemesh/govpp/issues/40
Also, nice to do https://github.com/networkservicemesh/govpp/issues/41
